apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-loop-driver
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-loop-driver
subjects:
  - kind: ServiceAccount
    name: csi-loop-driver
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-loop-driver
  apiGroup: rbac.authorization.k8s.io
